server:
  address: ":8001"
  openapiPath: "/api.json"
  swaggerPath: "/swagger"

database:
  default:
    link: "mysql:root:123456@tcp(106.13.219.71:3306)/iyyzh"
    debug: true

logger:
  level: "all"
  stdout: true