// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package logic

import (
	_ "iyyzh/internal/logic/user"
	_ "iyyzh/internal/logic/top"
)
