// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// User is the golang structure of table user for DAO operations like Where/Data.
type User struct {
	g.Meta      `orm:"table:user, do:true"`
	Id          interface{} // 主键
	UserName    interface{} // 姓名
	Sex         interface{} // 性别
	Age         interface{} // 年龄
	RealName    interface{} // 真实姓名
	Account     interface{} // 账号
	Password    interface{} // 密码
	Mobile      interface{} // 手机号码
	Address     interface{} // 居住地址
	Description interface{} // 个人简介
	Card        interface{} // 身份证号码
	State       interface{} // 用户状态1为正常2位禁用
}
