// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// User is the golang structure for table user.
type User struct {
	Id          uint   `json:"id"          ` // 主键
	UserName    string `json:"userName"    ` // 姓名
	Sex         string `json:"sex"         ` // 性别
	Age         uint   `json:"age"         ` // 年龄
	RealName    string `json:"realName"    ` // 真实姓名
	Account     string `json:"account"     ` // 账号
	Password    string `json:"password"    ` // 密码
	Mobile      string `json:"mobile"      ` // 手机号码
	Address     string `json:"address"     ` // 居住地址
	Description string `json:"description" ` // 个人简介
	Card        string `json:"card"        ` // 身份证号码
	State       int    `json:"state"       ` // 用户状态1为正常2位禁用
}
